### ISSUE TITLE
`new` subcommand can fail with a type error `string "" is not a function`

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/themis-contract#28]
```
2020-05-13 19:07:56 debug Attempting to load template as file: /home/sf/Sync/informal-systems/contracts/contract-templates/informal-shares-certificate/informal-shares-certificate-template.md
2020-05-13 19:07:56 debug Found potential template variable: share
2020-05-13 19:07:56 debug Found potential template variable: ordinal
2020-05-13 19:07:56 debug Found potential template variable: shareholder
2020-05-13 19:07:56 debug Found potential template variable: name
2020-05-13 19:07:56 debug Found potential template variable: certificate_date
2020-05-13 19:07:56 debug Found potential template variable: counterparties_list
2020-05-13 19:07:56 debug Found potential template variable: full_name
2020-05-13 19:07:56 debug Found potential template variable: signatories_list
2020-05-13 19:07:56 debug Found potential template variable: signature_image
2020-05-13 19:07:56 debug Found potential template variable: signature_image
2020-05-13 19:07:56 error string "" is not a function
TypeError: string "" is not a function
    at eval (eval at createFunctionContext (/home/sf/Sync/informal-systems/contracts/neat-contract/node_modules/handlebars/lib/handlebars/compiler/javascript-compiler.js:260:23), <anonymous>:11:5)
    at prog (/home/sf/Sync/informal-systems/contracts/neat-contract/node_modules/handlebars/lib/handlebars/runtime.js:333:12)
    at Proxy.<anonymous> (/home/sf/Sync/informal-systems/contracts/neat-contract/node_modules/handlebars/lib/handlebars/helpers/block-helper-missing.js:32:14)
    at Proxy.wrapper (/home/sf/Sync/informal-systems/contracts/neat-contract/node_modules/handlebars/lib/handlebars/internal/wrapHelper.js:10:19)
    at eval (eval at createFunctionContext (/home/sf/Sync/informal-systems/contracts/neat-contract/node_modules/handlebars/lib/handlebars/compiler/javascript-compiler.js:260:23), <anonymous>:11:69)
    at prog (/home/sf/Sync/informal-systems/contracts/neat-contract/node_modules/handlebars/lib/handlebars/runtime.js:333:12)
    at Proxy.<anonymous> (/home/sf/Sync/informal-systems/contracts/neat-contract/node_modules/handlebars/lib/handlebars/helpers/block-helper-missing.js:32:14)
    at Proxy.wrapper (/home/sf/Sync/informal-systems/contracts/neat-contract/node_modules/handlebars/lib/handlebars/internal/wrapHelper.js:10:19)
    at eval (eval at createFunctionContext (/home/sf/Sync/informal-systems/contracts/neat-contract/node_modules/handlebars/lib/handlebars/compiler/javascript-compiler.js:260:23), <anonymous>:13:98)
    at prog (/home/sf/Sync/informal-systems/contracts/neat-contract/node_modules/handlebars/lib/handlebars/runtime.js:333:12)
```

The section of the template it's dying on:

```
+--------------------+-----------------------------------------------------+
| Parties            | Signatories                                         |
+:===================+:====================================================+
{{#counterparties_list}}
|                    |                                                     |
+--------------------+-----------------------------------------------------+
| {{full_name}}                                                            |
{{#signatories_list}}
+--------------------+-----------------------------------------------------+
|                    |                                                     |
+--------------------+-----------------------------------------------------+
{{#signature_image}}
|                    |                                                     |
|                    | ![]({{&signature_image}})                           |
|                    |                                                     |
{{/signature_image}}
|                    |                                                     |
|                    | {{full_names}}                                      |
|                    |                                                     |
{{#title}}
|                    |                                                     |
|                    | Title: {{.}}                                        |
|                    |                                                     |
{{/title}}
|                    |                                                     |
|                    | Date: {{signed_date}}                               |
|                    |                                                     |
{{/signatories_list}}
+--------------------+-----------------------------------------------------+
{{/counterparties_list}}
```

Thank you unsound, gradual type checking!

**Comment by shonfeder** [comment]
Perhaps this bit of code in https://github.com/informalsystems/neat-contract/tree/master/src/shared/template-helpers.ts is responsible:

Seems likely to be originating in this function:

```
const makeVariableTrackerProxy = (parentObj: object, parents: string[], trackedVars: Map<string, any>): object => {
  return new Proxy(parentObj, {
    get: (target, name) => {
      if (typeof name === 'symbol') {
        return ''
      }
      if (name === 'toHTML') {
        return (): string => ''
      }
      const varName = String(name)
      logger.debug(`Found potential template variable: ${varName}`)
      trackVariable(trackedVars, parents, varName)
      return makeVariableTrackerProxy(target, [...parents, varName], trackedVars)
    },
  })
}
```

Both due to the log locations, and due to the fact this function can return either a `string` or a function `string -> string`. At some point, a consumer of the values from this function is getting that empty string out and trying to apply it as a function

**Comment by thanethomson** [comment]
As you mentioned on #29, this is a direct result of not explicitly specifying the `-t mustache` parameter. There's unfortunately no easy way for the tool to infer which templating language you want to use.

The `makeVariableTrackerProxy` function is ultimately a hack (and an ugly one at that), and one that should eventually rather be replaced by proper parsing of the template to expose its variables.

In the meantime, it should suffice to just catch this type of error during the execution of the `new` command and add a hint to the effect of: `(did you perhaps forget to specify the template type?)`.

**Comment by shonfeder** [comment]
Cool, I'll add that fix when I get a moment. Thanks!

**Comment by shonfeder** [comment]
What about changing the default templating language to be mustache too? It seems to me preferable, both because we are using it more pervasively, and because it's more constrained.

**Comment by thanethomson** [comment]
Sure, let's make Mustache the default 👍 I'll open an issue.
